### ISSUE TITLE
Add allow and receive

### ISSUE THREAD

**Issue by watzon** [icy-arctic-fox/spectator#2]
It would be great, although I don't know if it's quite possible, to have `allow` and `receive` which tend to work closely together. This would allow for us to make sure that certain methods are being called as the result of another method being called. For instance:

```crystal
allow(model).to receive(:fit_corpus).with(text)

it "calls its internal methods #fit_corpus to build the corpus obj" do
  expect(model).to receive(:fit_corpus).with(text)
  model.fit(text)
end
```

https://relishapp.com/rspec/rspec-mocks/v/2-14/docs/method-stubs

**Comment by icy-arctic-fox** [comment]
This happens to be a feature I'm currently working on! I've made some comments on the GitLab issue tracking this - https://gitlab.com/arctic-fox/spectator/issues/6 . Feedback would be greatly appreciated, especially since I'm prototyping it. (Don't feel like you have to use GitLab though).

As of now, the syntax would look something like this:

```crystal
Spectator.describe String do
  mock String do
    stub size { 5 }
  end

  it "returns the expected size" do
    string = "foobar"
    expect(string.size).to eq(5) # Not 6!
  end
end
```

and for doubles:

```crystal
double :foo do
  stub do_something { 42 }
end

it "does something" do
  dbl = double(:foo)
  expect(dbl.do_something).to eq(42)
end
```

The `receive` example:

```crystal
it "does something" do
  dbl = double(:foo)
  allow(dbl).to receive(do_something).and_return(42)
  expect(dbl.do_something).to eq(42)
  expect(dbl).to have_received(:do_something)
end
```

**Comment by watzon** [comment]
Damn man you're awesome! Can't wait to see this merged. Now that I think about it I definitely could've checked Gitlab, forgot this was hosted there.

**Comment by icy-arctic-fox** [comment]
Don't worry about it. I don't expect anyone to use GitLab.

I'm hoping to have this feature done within a month or so. Mocks are something I want for my own Crystal projects.

**Comment by watzon** [comment]
It would also be nice if we could do

```crystal
expect(foo).to receive(bar).exactly(1).times
```

or something similar

**Comment by icy-arctic-fox** [comment]
Good idea. I would have missed that. I want these to be as functionally equivalent to RSpec as possible. So ideally, all of these would be supported:

https://relishapp.com/rspec/rspec-mocks/v/3-8/docs/setting-constraints/receive-counts

I don't see any reason right now why those couldn't be implemented.

**Comment by icy-arctic-fox** [comment]
Just an update, there is a `mocks-and-doubles` branch in GitLab (which isn't mirrored to GitHub), that contains some functionality for this. If you're using a `shards.yml` and pointing to GitLab, you can start using it. The following code is possible:

```crystal
double :foo do
  stub bar { :bar }
  stub deferred : Int32
end

let(dbl) { double(:foo) }

it "detects stub calls" do
  dbl.bar
  expect(dbl).to have_received(bar)
end

it "detects deferred stub calls" do
  allow(dbl).to receive(deferred).and_return(42)
  dbl.deferred
  expect(dbl).to have_received(deferred)
end
```

More details on the [GitLab issue](https://gitlab.com/arctic-fox/spectator/issues/6) thread.

**Comment by icy-arctic-fox** [comment]
Another update.
There are some things I still need to work out with mocking real objects as well as statics (classes and modules).
Still quite a few little things to add for feature equivalence to RSpec.

Here's what new and on the [mocks-and-doubles](https://gitlab.com/arctic-fox/spectator/tree/mocks-and-doubles) branch:

Invoke different stubs based on arguments.
Provides the syntax:
`allow(DOUBLE).to receive(METHOD).with(ARGS...).and_return(VALUE)`

```crystal
  double :foo do
    stub with_args(foo) { foo.to_s } # Default stub
  end
  let(dbl) { double(:foo) }

  context "argument matching" do
    before_each { allow(dbl).to receive(with_args).with(Symbol).and_return("foo") } # Stub 1
    before_each { allow(dbl).to receive(with_args).with(Float).and_return("bar") }  # Stub 2
    before_each { allow(dbl).to receive(with_args).with(123).and_return(:asdf) }    # Return type doesn't match, error.

    it "stubs matching arguments" do
      expect(dbl.with_args(:bar)).to eq("foo") # Calls stub 1
      expect(dbl.with_args(0.0)).to eq("bar")  # Calls stub 2
      expect { dbl.with_args(123) }.to raise_error(/return type/)
    end

    it "doesn't stub non-matching arguments" do
      expect(dbl.with_args(42)).to eq("42") # Calls default stub
    end
  end
```

Match the arguments sent to the stub.
Provides this syntax:
`have_received(METHOD).with(ARGS...)`

```crystal
  double :foo do
    stub with_args(foo) { foo.to_s } # Default stub
  end
  let(dbl) { double(:foo) }

  context "argument matching" do
    it "reports matching arguments" do
      dbl.with_args(:foo)
      expect(dbl).to have_received(with_args).with(Symbol)
    end
  end
```

Number of invocations.
Provides the following modifiers:
- `once`
- `twice`
- `exactly(COUNT).times`
- `at_least(COUNT).times`
- `at_most(COUNT).times`
- `at_least_once`
- `at_least_twice`
- `at_most_once`
- `at_most_twice`

```crystal
  double :foo do
    stub with_args(foo) { foo.to_s } # Default stub
  end
  let(dbl) { double(:foo) }

  context "invocation count" do
    it "tracks number of invocations" do
      3.times { dbl.with_args(:foo) }
      expect(dbl).to have_received(with_args).with(Symbol).at_least_once
    end
  end
```

Mocks (real object stubbing) is experimental.
Use at your own risk!
Looks similar to doubles:

```crystal
  # This example will segfault.
  mock String do
    stub size { 42 }
  end

  context "mocks" do
    it "stubs real objects" do
      expect("foobar".size).to eq(42)
    end
  end
```

**Comment by watzon** [comment]
So exciting! I'm so ready to have this feature available

**Comment by icy-arctic-fox** [comment]
Yet another update. The features are mostly complete. There are a few things that I would like to add before it's released. I hope to have this rolled out soon!

The following still needs to be implemented:
- Call original - `expect(Calculator).to receive(:add).and_call_original`
- Wrap original - `expect(API).to receive(:solve_for).and_wrap_original { |m, *args| m.call(*args).first(5) }`
- Block implementation - `allow(dbl).to receive(:foo) { 14 }` This is really easy.
- Verifying doubles - `double(SomeClass)` verify the methods called on the double are implemented on `SomeClass`.

Mocks and doubles are fully implemented. I expect there to be some issues found later, however. There's also quite a bit of cleanup I want to do, but that can wait.

Anonymous doubles have been added, which removes the need to pre-define a double outside of a test. Using it still requires defining methods up-front though.

```crystal
it "does something" do
  dbl = double(five: 5)
  expect(dbl.five).to eq(5)
end
```

Most of the features listed in the [RSpec docs](https://relishapp.com/rspec/rspec-mocks/v/3-8/docs) has been implemented in one way or another.

The attached file is what I have been using to test with. It takes examples straight from the RSpec docs. Changes have been documented.
[test_rspec.cr.txt](https://github.com/icy-arctic-fox/spectator/files/3861763/test_rspec.cr.txt)

**Comment by watzon** [comment]
That's awesome. I've been waiting for this to be able to add specs to some of my libraries, so I'll definitely be trying it out soon. Great work!

**Comment by icy-arctic-fox** [comment]
This feature just released to master. Version 0.9.0 of the shard should have this functionality. I plan on adding more functionality to mocks and doubles, but wanted to get something tangible out to users.

Let me know what you think and if this suits your needs. Documentation coming soon-ish.

**Comment by watzon** [comment]
Woo so exciting! As soon as I have some time to add tests to a couple of my libraries that are missing them I'll let you know how it goes.

**Comment by icy-arctic-fox** [comment]
I think this issue can finally be called done. The documentation for mocks and doubles has been written. I'll probably revisit and improve upon the functionality. Any additional work for mocks and doubles will be in a new issue.

Docs are available here: https://gitlab.com/arctic-fox/spectator/-/wikis/Mocks-and-Doubles
Specifically for `expect().to receive`: https://gitlab.com/arctic-fox/spectator/-/wikis/Stub-Expectations#receive
Specifically for `allow().to receive`: https://gitlab.com/arctic-fox/spectator/-/wikis/Stubs
