### ISSUE TITLE
Stubbing [] methods

### ISSUE THREAD

**Issue by yunusemredilber** [icy-arctic-fox/spectator#21]
I want to create a class mock that has the following method:
```cr
def [](key : String)
  find_key key
end
```

I couldn't find a way to stub that. When I try something like this:
```cr
mock MyMock do
  stub [](key)
end
```

It produces an error like this:
```
 7 | stub [](name)
          ^
Error: for empty arrays use '[] of ElementType'
```

Is there any way to achieve this?

**Comment by icy-arctic-fox** [comment]
There is a way to do this, it isn't document yet. Sorry about that! There is an alternate syntax for stubbing that uses symbols for the method name. This is part of #14 

This is how it looks:

```crystal
mock MyMock do
  stub :[], key
end
```

and to provide a default implementation:

```crystal
mock MyMock do
  stub :[], key { "some value" }
end
```

**Comment by yunusemredilber** [comment]
Thanks for the explanation @icy-arctic-fox 😄
