### ISSUE TITLE
Allow matching any line in spec grouping

### ISSUE THREAD

**Issue by matthewmcgarvey** [icy-arctic-fox/spectator#24]
Related to https://github.com/icy-arctic-fox/spectator/issues/19 but expanded to support passing a line number within the grouping of a spec.  If the line number matches a context block, every spec within that context should be run. The same goes for the describe block. If the line number falls on a specific spec then that should be run specifically, still.

**Comment by icy-arctic-fox** [comment]
Implemented in v0.10
