### ISSUE TITLE
Cannot use be_kind_of() with described_class

### ISSUE THREAD

**Issue by postmodern** [icy-arctic-fox/spectator#25]
Ran into this odd error:

```
 256 | expect(super_set).to be_kind_of(described_class)
                                       ^
Error: unexpected token: described_class
```

The entire spec block:

```crystal
  describe "#|" do
    it "should be able to be unioned with another set of chars" do
      super_set = (subject | described_class['0'])

      expect(super_set).to be_kind_of(described_class)
      expect(super_set.includes_char?('0')).to be(true)
    end
  end
```

Clearly I'm using `described_class` before the offending line, but for some reason the compiler does not like `described_class` being passed/expanded within `be_kind_of`.

**Comment by icy-arctic-fox** [comment]
I think this is because the matcher expected a type literal, such as `String` or `Int32`. I've pushed a change that will hopefully fix it. Can you try with the latest code from master and let me know if it works?

**Comment by postmodern** [comment]
@icy-arctic-fox `master` works. Thanks!

**Comment by icy-arctic-fox** [comment]
Cut a new release - v0.9.35 which contains the fix.
