### ISSUE TITLE
Add HTML as a format option

### ISSUE THREAD

**Issue by watzon** [icy-arctic-fox/spectator#3]
Just another thing that rspec has that would be wonderful to have here is the `--format html` command line flag. Idk if you already have it planned, but it's not on the roadmap so I figured I'd put it here.

**Comment by icy-arctic-fox** [comment]
I had no idea that RSpec had a built-in HTML formatter. It's not even in the docs. That is certainly something that should be added. Probably won't copy the visuals that RSpec uses though, it looks kind of ugly.

Link to GitLab issue: https://gitlab.com/arctic-fox/spectator/issues/22

**Comment by watzon** [comment]
I agree 100% on that front, I'm sure you can do a better job. Tbh you may even think about using [SushiChain/spinach](https://github.com/SushiChain/spinach) as inspiration. He did a pretty good job of making things look good.

**Comment by icy-arctic-fox** [comment]
Implemented in v0.10
