### ISSUE TITLE
Example of custom matcher does not compile

### ISSUE THREAD

**Issue by gmartsenkov** [icy-arctic-fox/spectator#46]
The example here fails to compile - https://github.com/icy-arctic-fox/spectator/wiki/Custom-Matchers 
It fails with `Error: undefined constant ::Spectator::TestValue`.  
Tried changing that to `Spectator::Value` which seems to be the new name but that fails with:
```crystal
no overload matches 'MultipleOfMatcher(ExpectedType).new' with type Spectator::Value(Int32)
```

Also thanks for the wonderful library you've built!

**Comment by icy-arctic-fox** [comment]
There were a couple of issues here.

1. The docs for custom matchers were outdated and referenced old types. The `Test` prefix was dropped a while ago. The docs have been updated to reflect this.
2. For some reason, `Spectator::Value(T)` was not resolving properly when defining a matcher outside of the `Spectator` module.

The second issue should be resolved in the latest release (v0.11.3).

If this issue isn't resolved, please reopen. Thanks!
