### ISSUE TITLE
Print random seed?

### ISSUE THREAD

**Issue by m-o-e** [icy-arctic-fox/spectator#7]
Thanks for this great shard, works splendidly for me! 🙇 

Super minor thing I noticed:
It doesn't seem to print the random seed when `-r` is given.

Would be nice if it could do that, so that a failure that
depends on test-order can be easily reproduced.

**Comment by icy-arctic-fox** [comment]
Glad to hear it works great for you!

This has been implemented in 0.9.21, which was just released.

**Comment by m-o-e** [comment]
Thanks a lot! 🙇
