### ISSUE TITLE
Allow contain(*elements)

### ISSUE THREAD

**Issue by postmodern** [icy-arctic-fox/spectator#8]
I noticed that `contain` automatically wraps the given argument in `{ }` as a Tuple. It would be useful to be able to call `contain()` with multiple splatted arguments.

### Example

    alias ArgsTuple = Tuple(String, Extractor::MetaType, Extractor::MetaFormat, String, Extractor::MetaData)
    
    let(metadata_file) { File.join(fixtures_dir,"image-metadata.yml") }
    let(expected_metadata) do
      Array(ArgsTuple).from_yaml(File.read(metadata_file))
    end
    
    it "should extract metadata from a file" do
      findings = [] of ArgsTuple

      subject.extract(data) do |plugin_name,type,format,mime_type,data|
        findings << {plugin_name, type, format, mime_type, data}
      end

      expect(findings).to contain(*expected_metadata)
    end

### Result

    Code in spec/extractor_spec.cr:53:27
    
     53 | expect(findings).to contain(*expected_metadata)
                              ^
    Called macro defined in lib/spectator/src/spectator/dsl/matchers.cr:452:5
    
     452 | macro contain(*expected)
    
    Which expanded to:
    
     > 1 | __temp_1618 = ::Spectator::TestValue.new({*expected_metadata}, "*expected_metadata")
                                                   ^
    Error: unterminated call

**Comment by icy-arctic-fox** [comment]
This can be worked around (and might be preferred) to use the [`match_array` matcher](https://github.com/icy-arctic-fox/spectator/wiki/Collection-Matchers#match_array) instead.

This should work, since it's valid Crystal syntax, so I'll look at providing a fix.

**Comment by postmodern** [comment]
In my example `findings` can contain exactly the `expected_metdata` Array of Tuples when it's ran on my machine. When I run the specs on a Ubuntu system with Ubuntu's version of libextractor, then additional Tuples show up in `findings`. So I need something like RSpec's `.to include(*array)`.

**Comment by icy-arctic-fox** [comment]
Would a non-splat version of `contain` work? That looks faster/easier to implement than fixing splatting within `contain` for now. Perhaps something like `contain_elements(array_or_tuple)`?

**Comment by postmodern** [comment]
Could we overload `contain` to accept an `Array(Tuple)`?

**Comment by icy-arctic-fox** [comment]
There should be a fix in the latest version (0.9.22). Can you see if that works for you? This snippet worked for me:

```cr
Spectator.describe "GitHub Issue 8" do
  it "works without a splat" do
    expect([1, 2, 3, 4, 5]).to contain(2, 3, 4)
  end

  it "works with a splat" do
    elements = {2, 3, 4}
    expect([1, 2, 3, 4, 5]).to contain(*elements)
  end
end
```

**Comment by postmodern** [comment]
Excellent. It compiles now. Still failing due to another weird equality issue that I'm still investigating; the same code works if I write it as plain crystal code and compare the two `Array(Tuple)` objects with `==`.

**Comment by icy-arctic-fox** [comment]
> Excellent. It compiles now. Still failing due to another weird equality issue that I'm still investigating; the same code works if I write it as plain crystal code and compare the two `Array(Tuple)` objects with `==`.

Please let me know if you find an issue with this. That sounds like it could be a big issue.

The `contain` matcher uses this for its check:

```cr
expected.value.all? do |item|
  actual.includes?(item)
end
```

The `includes?` method uses the `==` operator, should everything should be okay...
https://github.com/crystal-lang/crystal/blob/5999ae29b/src/enumerable.cr#L616
